### ISSUE TITLE
Provide adding and removing desktop shortcuts in the right-click menu

### ISSUE THREAD

**Issue by SnDream** [dhruv8sh/plasma6-desktop-indicator#2]
Is it possible to provide adding and removing desktop shortcuts in the right-click menu, like plasma's default addon?
On top of that, it would be nice to have a menu item for desktop renaming.

**Comment by dhruv8sh** [comment]
Yes. I have been thinking about adding this too. This will be added in the next release.

**Comment by dhruv8sh** [comment]
Added alongside some other minor improvements.
