### ISSUE TITLE
Show indicator on desktops that contains windows

### ISSUE THREAD

**Issue by Amjad50** [dhruv8sh/plasma6-desktop-indicator#4]
Hello

It would be nice to show a small indicator maybe a change color or a different icon for desktop that contain any window.

Currently, there is `active` and `inactive` states, so something like `active`, `inactive`, `used`.

Thanks

**Comment by dhruv8sh** [comment]
#1 is the exact same, look there for more details.
Continue this conversation there. But do let me know if you have ever used an applet in KDE with this functionality.
